name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  EKS_CLUSTER_NAME: netflix-clone-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/netflix-clone:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/netflix-clone:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: kubectl apply -f k8-Manifest/

      - name: Force image update
        run: |
          kubectl set image deployment/netflix-app \
          netflix-app=${{ secrets.DOCKER_USERNAME }}/netflix-clone:latest --record

